<?php
/**
 * Created by PhpStorm.
 * User: GCLion
 * Date: 2019/1/26
 * Time: 22:29
 */

namespace backend\controllers;


use backend\modules\admin\models\User;
use backend\modules\system\models\Node;
use yii\web\Controller;
use Yii;

class CommonController extends Controller
{
    public $data = [
        'js'=>[],'css'=>[]
    ];

    protected $username;
    protected $token;

    public $node;

    public function init()
    {
        if($this->is_login() && $this->modules){
            if($this->module->id == 'system' && $this->id == 'default'){
                return $this->redirect('admin/admin/index');
            }

            $nodes_list = Yii::$app->session['node_list'];
            if($nodes_list){
                $nodes_list = unserialize($nodes_list);
            }else{
                # 查询node节点
                $nodes_list = Node::find()->where('status= :status ',[':status'=>1])->orderBy(['sort'=>SORT_ASC])->asArray()->all();
                if($nodes_list){
                    Yii::$app->session['node_list'] = serialize($nodes_list);
                }
            }

            $list = $this->list_to_tree($nodes_list);

            $this->node = $list;

        }else{
            Yii::$app->session['node_list'] = '';

            return $this->redirect('/system/login/login');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function beforeAction($action)
    {
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


    /*
     * 检查登陆
     *
     *
     */
    public function is_login()
    {
        if(Yii::$app->session['uid'] && Yii::$app->session['username'] && Yii::$app->session['token']){
            return true;
        }else{
            return false;
        }
    }


    /*
     * 数组转树形
     * @param $list
     * @param $pid
     *
     * @return array
     */
    public function list_to_tree($list,$pid = 0){
        if(empty($list) || !is_array($list) ) return [];
        $current_url = '/'.Yii::$app->request->pathInfo;

        $_child = [];

        foreach ($list as $k=>$v){
            if($v['pid'] == $pid){
                if($v['level'] == 1 && $v['module'] == $this->module->id){
                    $v['is_open'] = 1;
                }else{
                    $v['is_open'] = 0;
                }

                $v['_child'] = $this->list_to_tree($list,$v['id']);

                if($v['level'] == 2) {
                    if($v['url'] == $current_url){
                        $v['is_active'] = 1;
                    }else{
                        # 查询子级
                        $child_url_array = array_column($v['_child'],'url');
                        if(in_array($current_url,$child_url_array)){
                            $v['is_active'] = 1;
                        }else{
                            $v['is_active'] = 0;
                        }
                    }
                }

                $_child[]    = $v;
            }
        }
        if(empty($_child)){
            return [];
        }else{
            return $_child;
        }
    }


    /**
     * 将所点击的列表项以及其父列表项的state置1
     *
     * @param $menu_arr 菜单栏配置信息
     * @param $url      点击的链接
     * @return array|bool
     */
    function getMenu($menu_arr,$url){

        if (!is_array($menu_arr)){
            return false;
        }

        for ($i = 0;$i < count($menu_arr);$i++){
            if (array_key_exists('url',$menu_arr[$i]) && !empty($menu_arr[$i]['url'])){
                $menu_url = strtolower($menu_arr[$i]['url']);
                $url = strtolower($url);
                $menu_url = explode('.',$menu_url)[0];
                $url  = explode('.',$url)[0];

//            比对点击的url和配置信息中的url是否一致
                if (strpos($menu_url,$url) !== false){
                    $menu_arr[$i]['state'] = 1;
                    return $menu_arr;
                }else{

//                多个url绑定到一个列表项
                    if (array_key_exists('other',$menu_arr[$i]) && !empty($menu_arr[$i]['other'])){
                        for ($j = 0;$j < count($menu_arr[$i]['other']);$j++){
                            $other_url = $menu_arr[$i]['other'][$j];
                            $other_url = explode(',',strtolower($other_url))[0];
                            if (strpos($other_url,$url) !== false){

                                $menu_arr[$i]['state'] = 1;
                                return $menu_arr;
                            }
                        }
                    }
                }
            }else{
                if (array_key_exists('sub',$menu_arr[$i])){
//                继续进行递归搜索
                    $sub = getMenu($menu_arr[$i]['sub'],$url);

                    if ($sub == $menu_arr[$i]['sub']){
                        $menu_arr[$i]['state']=0;
                    }else{
                        $menu_arr[$i]['state']=1;
                    }

                    $menu_arr[$i]['sub'] = $sub;
                }
            }
        }

        return $menu_arr;
    }



}







