<?php
/**
 * Created by PhpStorm.
 * User: GCLion
 * Date: 2019/1/17
 * Time: 22:55
 */

namespace frontend\controllers;
use yii;
use yii\web\Controller;

class CommonController extends Controller
{
    public $data = [
        'js'=>[],
        'css'=>[]
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}