<?php
/**
 * Created by PhpStorm.
 * User: GCLion
 * Date: 2019/1/26
 * Time: 22:29
 */

namespace backend\modules\system\controllers;

use backend\models\CommonModel;
use backend\modules\admin\models\User;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\web\Controller;
use Yii;
use yii\web\Response;

class LoginController extends Controller
{
    public $enableCsrfValidation=false;

    public $layout = '@backend/views/layouts/login.php';
    public $data = [
        'js'=>[],'css'=>[]
    ];
    public function init()
    {
        $uid      = Yii::$app->session['uid'];
        $username = Yii::$app->session['username'];
        $token    = Yii::$app->session['token'];
        if($uid && $username && $token){
            return $this->redirect('/category/manage/index');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login','logout','dologin', 'error'],
                        'allow' => true,
                    ],
                ],
            ],
        ];


        return parent::behaviors(); // TODO: Change the autogenerated stub


    }

    public function actions()
    {
        return parent::actions(); // TODO: Change the autogenerated stub
    }

    # 登陆页面
    public function actionLogin()
    {
        $this->data['js'] = [
            'static/common/js/jquery.validate.min.js',
            'static/js/login.js'
        ];

        return $this->render('index',$this->data);
    }


    # 登陆验证
    public function actionDologin()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        $username = Yii::$app->request->post('username','');
        $password = Yii::$app->request->post('password','');

        if(!$username) return array('status'=>0,'msg'=>'用户名不能为空');
        if(!$password) return array('status'=>0,'msg'=>'密码不能为空');
        if(!CommonModel::validatePassword($username,$password)) return array('status'=>0,'msg'=>'用户名或者密码不正确');

        $uid = CommonModel::validatePassword($username,$password);
        $userModel = User::findOne($uid);
        $userModel->last_login_times = time();

        $result = false;
        if($userModel->validate()){
            $result = $userModel->save();
        }
        if($result !== false){
            $token = CommonModel::createToken($username,$userModel->password);

            Yii::$app->session['uid']       = $uid;
            Yii::$app->session['username']  = $username;
            Yii::$app->session['name']      = $userModel->name;
            Yii::$app->session['tel']       = $userModel->tel;
            Yii::$app->session['token']     = $token;

            return ['status'=> 1,'msg'=>'登陆成功','data'=>[
                'uid'=>$uid,
                'username'=>$username,
                'name'=>$userModel->name,
                'tel'=>$userModel->tel,
                'token'=>$token
            ]];
        }else{
            return ['status'=>0,'msg'=>'登陆失败'];
        }
    }

    # 登出
    public function actionLogout()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;

        Yii::$app->session->destroy();

        return ['status'=>1,'msg'=>'登出成功'];
    }
}